# build Configuration, i.e. Debug, Release, etc. 
configuration: 
  - Debug 
  - Release 

build: 
  parallel: true                   

environment:
  SolutionDir: $(APPVEYOR_BUILD_FOLDER)/Trunk/Source
