# build Configuration, i.e. Debug, Release, etc. 
configuration: 
 - Debug 
#  - Release 

build: 
 parallel: true                   
 project: $(project_name)
 verbosity: detailed 

environment:
 SolutionDir: $(APPVEYOR_BUILD_FOLDER)
 matrix:
  - project_name: Trunk/Source/LeaveManagement-outlook.sln
 pfx_secret:
  secure: 65n6AyPYcgulP7Sgn2/Wrw==

# before build scripts 
before_build: 
 - ps: Import-PfxCertificate -FilePath .\Trunk\Source\LeaveManagement.OutlookAddIn2010\TemporaryKey.pfx -CertStoreLocation cert:\CurrentUser\My 

build_script: 
 - msbuild .\Trunk\Source\LeaveManagement.OutlookAddIn2010\LeaveManagement.OutlookAddIn2010.csproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /t:Publish /p:PublishUrl=c:\projects 

install:
 - nuget install secure-file -ExcludeVersion
 - secure-file\tools\secure-file -decrypt .\Trunk\Source\LeaveManagement.OutlookAddIn2010\TemporaryKey.pfx.enc -secret %pfx_secret%
 - appveyor DownloadFile http://blockworks.com/Media/Default/LeaveManagement/vsto-pack.zip
 - 7z x -oC:\ vsto-pack.zip
 - reg import C:\vsto1.reg
 - reg import C:\vsto2.reg
 - reg import C:\vsto3.reg
 - reg import C:\vsto4.reg

